"""Export the strategies as TradingView Pine Script v6.

TradingView cannot run this Python package, so the strategies are emitted as
native Pine strategies instead. They mirror the Python versions deliberately:

* the same stance rules and default parameters
* the same risk block: percentage stop, trailing stop, optional target
* the same execution timing, since Pine with ``process_orders_on_close=false``
  fills on the next bar's open, exactly as this engine does

They will not match the Python backtest to the cent. TradingView uses its own
data, its own dividend adjustment, and its own intrabar fill assumptions. Treat
a large divergence as a question worth asking, not as proof either side is
wrong.
"""

from __future__ import annotations

from typing import Dict

from .strategies import REGISTRY

INSTRUCTIONS = """
To use these on TradingView:

  1. Open a chart, then the Pine Editor tab at the bottom of the screen.
  2. Open a new blank strategy, select all of the placeholder code, delete it.
  3. Paste the contents of one .pine file.
  4. Click Save, give it a name, then Add to chart.
  5. The Strategy Tester tab at the bottom shows the backtest results.

Set the chart to Daily before judging any of these. They are daily bar
strategies, and running them on a 5 minute chart tests something else entirely.

A free TradingView account limits how much history the Strategy Tester covers,
so its numbers will differ from a long Python backtest for that reason alone.
"""

_HEADER = """//@version=6
// {title}
// Generated by tradingbot. Mirrors the Python strategy of the same name.
//
// Execution timing matches the Python engine: process_orders_on_close is false,
// so a signal computed on this bar's close is filled at the next bar's open.
strategy("{title}", overlay={overlay}, initial_capital=10000,
     default_qty_type=strategy.percent_of_equity, default_qty_value=20,
     commission_type=strategy.commission.percent, commission_value=0.0,
     slippage=1, process_orders_on_close=false, calc_on_every_tick=false,
     pyramiding=0)

// ---------------------------------------------------------------- direction
dirMode = input.string("long", "Direction", options=["long", "short", "both"],
     tooltip="Which sides this strategy may take. Shorting carries unlimited loss exposure.")
allowLong  = dirMode == "long"  or dirMode == "both"
allowShort = dirMode == "short" or dirMode == "both"
"""

_RISK_BLOCK = """
// -------------------------------------------------------------------- risk
grpRisk   = "Risk"
useStop   = input.bool(true,  "Stop loss",     group=grpRisk)
stopPct   = input.float(8.0,  "Stop loss %",   minval=0.1, maxval=90, step=0.5, group=grpRisk)
useTrail  = input.bool(false, "Trailing stop", group=grpRisk)
trailPct  = input.float(15.0, "Trailing %",    minval=0.1, maxval=90, step=0.5, group=grpRisk)
useTarget = input.bool(false, "Take profit",   group=grpRisk)
targetPct = input.float(20.0, "Take profit %", minval=0.1, step=0.5, group=grpRisk)

// --------------------------------------------------------------- execution
// stance: 1 wants long, -1 wants short, 0 wants flat, na means leave it alone.
// Everything below is top level rather than inside functions, because Pine
// places restrictions on strategy calls made from user defined functions.
posSign = math.sign(strategy.position_size)
target  = na(stance) ? posSign : stance
target := not allowLong  and target > 0 ? 0.0 : target
target := not allowShort and target < 0 ? 0.0 : target

if target > 0 and posSign <= 0
    strategy.entry("long", strategy.long)
else if target < 0 and posSign >= 0
    strategy.entry("short", strategy.short)
else if target == 0 and posSign != 0
    strategy.close_all(comment="signal neutral")

// Water marks for the trailing stop, tracked on closes exactly as the Python
// engine does. Computing the stop price explicitly avoids Pine's ambiguity
// over whether trail_offset is measured in ticks or in price.
var float hiWater = na
var float loWater = na
if strategy.position_size == 0
    hiWater := na
    loWater := na
else
    hiWater := na(hiWater) ? close : math.max(hiWater, close)
    loWater := na(loWater) ? close : math.min(loWater, close)

entryPx = strategy.position_avg_price

if strategy.position_size > 0
    float longStop = useStop ? entryPx * (1 - stopPct / 100) : na
    if useTrail and not na(hiWater)
        trailStop = hiWater * (1 - trailPct / 100)
        longStop := na(longStop) ? trailStop : math.max(longStop, trailStop)
    float longTarget = useTarget ? entryPx * (1 + targetPct / 100) : na
    strategy.exit("exit long", from_entry="long", stop=longStop, limit=longTarget)

if strategy.position_size < 0
    float shortStop = useStop ? entryPx * (1 + stopPct / 100) : na
    if useTrail and not na(loWater)
        trailStop = loWater * (1 + trailPct / 100)
        shortStop := na(shortStop) ? trailStop : math.min(shortStop, trailStop)
    float shortTarget = useTarget ? entryPx * (1 - targetPct / 100) : na
    strategy.exit("exit short", from_entry="short", stop=shortStop, limit=shortTarget)
"""


_FOOTER = """
// Educational software. Backtested results routinely fail to repeat live.
"""


_BODIES: Dict[str, Dict[str, str]] = {
    "sma_crossover": {
        "title": "SMA Crossover [tradingbot]",
        "overlay": "true",
        "body": """
// ------------------------------------------------------------------ inputs
fastLen = input.int(20, "Fast SMA", minval=1)
slowLen = input.int(50, "Slow SMA", minval=2)

fast = ta.sma(close, fastLen)
slow = ta.sma(close, slowLen)

plot(fast, "Fast SMA", color=color.new(color.aqua, 0))
plot(slow, "Slow SMA", color=color.new(color.orange, 0))

// Long while the fast average leads the slow one, short while it lags.
stance = na(fast) or na(slow) ? na : (fast > slow ? 1.0 : -1.0)
""",
    },
    "macd_trend": {
        "title": "MACD Trend [tradingbot]",
        "overlay": "false",
        "body": """
// ------------------------------------------------------------------ inputs
fastLen   = input.int(12,  "MACD fast",     minval=1)
slowLen   = input.int(26,  "MACD slow",     minval=2)
sigLen    = input.int(9,   "Signal",        minval=1)
trendLen  = input.int(200, "Trend filter SMA (0 disables)", minval=0)

[macdLine, signalLine, hist] = ta.macd(close, fastLen, slowLen, sigLen)
trendMa = trendLen > 0 ? ta.sma(close, trendLen) : na

plot(hist,       "Histogram", style=plot.style_columns,
     color=hist >= 0 ? color.new(color.green, 40) : color.new(color.red, 40))
plot(macdLine,   "MACD",   color=color.new(color.blue, 0))
plot(signalLine, "Signal", color=color.new(color.orange, 0))

// The long term trend vetoes taking the opposite side.
aboveTrend = trendLen > 0 ? close > trendMa : true
stanceRaw = na(hist) ? na : (hist > 0 ? 1.0 : -1.0)
stance = na(stanceRaw) ? na :
     trendLen == 0 ? stanceRaw :
     na(trendMa) ? na :
     stanceRaw > 0 ? (aboveTrend ? 1.0 : 0.0) : (aboveTrend ? 0.0 : -1.0)
""",
    },
    "rsi_reversion": {
        "title": "RSI Mean Reversion [tradingbot]",
        "overlay": "false",
        "body": """
// ------------------------------------------------------------------ inputs
rsiLen     = input.int(14,    "RSI length",  minval=2)
oversold   = input.float(30., "Oversold",    minval=1, maxval=99)
overbought = input.float(55., "Overbought",  minval=1, maxval=99)
trendLen   = input.int(200,   "Trend filter SMA (0 disables)", minval=0)

rsi     = ta.rsi(close, rsiLen)
trendMa = trendLen > 0 ? ta.sma(close, trendLen) : na

plot(rsi, "RSI", color=color.new(color.purple, 0))
hline(oversold,   "Oversold",   color=color.new(color.green, 50))
hline(overbought, "Overbought", color=color.new(color.red, 50))

aboveTrend = trendLen > 0 ? close >= trendMa : true
// Buy oversold inside an uptrend, short overbought inside a downtrend.
stance = na(rsi) ? na :
     (trendLen > 0 and na(trendMa)) ? na :
     rsi <= oversold   ? (aboveTrend ? 1.0 : 0.0) :
     rsi >= overbought ? (aboveTrend ? 0.0 : -1.0) : na
""",
    },
    "donchian_breakout": {
        "title": "Donchian Breakout [tradingbot]",
        "overlay": "true",
        "body": """
// ------------------------------------------------------------------ inputs
entryLen = input.int(20, "Entry channel", minval=2)
exitLen  = input.int(10, "Exit channel",  minval=1)

// Compare against the channel as of the previous bar, so the breakout bar does
// not set the level it is breaking.
upper     = ta.highest(high, entryLen)[1]
lowerEnt  = ta.lowest(low,   entryLen)[1]
upperExit = ta.highest(high, exitLen)[1]
lowerExit = ta.lowest(low,   exitLen)[1]

plot(upper,    "Entry high", color=color.new(color.green, 30))
plot(lowerEnt, "Entry low",  color=color.new(color.red, 30))

stance = na(upper) or na(lowerEnt) ? na :
     close > upper    ? 1.0 :
     close < lowerEnt ? -1.0 :
     (not na(lowerExit) and close < lowerExit) ? 0.0 :
     (not na(upperExit) and close > upperExit) ? 0.0 : na
""",
    },
    "bollinger_reversion": {
        "title": "Bollinger Reversion [tradingbot]",
        "overlay": "true",
        "body": """
// ------------------------------------------------------------------ inputs
bbLen  = input.int(20,    "Length",             minval=2)
bbMult = input.float(2.0, "Standard deviations", minval=0.1, step=0.1)

basis = ta.sma(close, bbLen)
dev   = bbMult * ta.stdev(close, bbLen)
upper = basis + dev
lower = basis - dev

plot(basis, "Basis", color=color.new(color.orange, 0))
p1 = plot(upper, "Upper", color=color.new(color.gray, 0))
p2 = plot(lower, "Lower", color=color.new(color.gray, 0))
fill(p1, p2, color=color.new(color.blue, 92))

// Fade the bands, exit back at the mean.
atMean = not na(basis) and math.abs(close - basis) / basis < 0.002
stance = na(basis) or na(upper) or na(lower) ? na :
     close < lower ? 1.0 :
     close > upper ? -1.0 :
     atMean ? 0.0 : na
""",
    },
    "buy_and_hold": {
        "title": "Buy and Hold [tradingbot]",
        "overlay": "true",
        "body": """
// The benchmark. Buy on the first bar and never sell. Whatever strategy you
// are considering has to beat this line after costs, or it is not worth running.
stance = 1.0
""",
    },
}


def generate(name: str) -> str:
    """Return the Pine Script source for one registered strategy."""
    if name not in REGISTRY:
        raise ValueError(
            f"unknown strategy {name!r}; available: {', '.join(sorted(REGISTRY))}"
        )
    if name not in _BODIES:
        raise ValueError(f"no Pine Script template for {name!r}")
    spec = _BODIES[name]
    header = _HEADER.format(title=spec["title"], overlay=spec["overlay"])
    return header + spec["body"] + _RISK_BLOCK + _FOOTER


def generate_all() -> Dict[str, str]:
    return {name: generate(name) for name in sorted(_BODIES)}
